<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use AppBundle\Entity\Category3;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia {
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var Category3
     */
    protected $category;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @return Category3
     */
    public function getCategory() {
        return $this->category;
    }

    // NEXT_MAJOR: Uncomment this method and remove __call and __set
    /**
     * @param Category3|null $category
     */
    public function setCategory( $category = null ) {
        $this->category = $category;
    }
}
