<?php

namespace AppBundle\Repository;

/**
 * BannerMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
