<?php

namespace AppBundle\Repository;

/**
 * CategoriesPicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesPicturesRepository extends \Doctrine\ORM\EntityRepository
{
}
