<?php

namespace AppBundle\Repository;

/**
 * FrameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameRepository extends \Doctrine\ORM\EntityRepository {
    /**
     * Return query for getting list of frames.
     *
     * @return \Doctrine\ORM\Query
     */
    public function getFrameList() {
        return $this->createQueryBuilder( 'f' )
                    ->where( 'f.isActive = true' )
                    ->innerJoin( 'f.frameMaterial', 'm' )// Inner Join with picture forms
                    ->getQuery();
    }
}
