<?php

namespace AppBundle\Repository;

/**
 * FrameColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameColorRepository extends \Doctrine\ORM\EntityRepository
{
}
