<?php

namespace AppBundle\Repository;

/**
 * FrameMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
