<?php

namespace AppBundle\Repository;

/**
 * MatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatRepository extends \Doctrine\ORM\EntityRepository
{
}
