<?php

namespace AppBundle\Repository;

/**
 * ModuleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
