<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OwnPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnPictureRepository extends EntityRepository {
    public function getOwnPicturesForMyFiles( $ids ) {
        return $this->createQueryBuilder( 'o' )
            ->where( 'o.id IN (:ids)' )
            ->setParameter( 'ids', $ids );
    }

    public function getOwnPicturesForClean( $ids ) {
        $q = $this->createQueryBuilder( 'o' );
        if(!empty($ids)) {
            $q->where( 'o.id NOT IN (:ids)' )
                ->setParameter( 'ids', $ids );
        }

        return $q->getQuery()->getResult();
    }
}
