<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OwnPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnPictureRepository extends EntityRepository {
    public function getOwnPicturesForMyFiles( $ids ) {
        return $this->createQueryBuilder( 'o' )
            ->where( 'o.id IN (:ids)' )
            ->setParameter( 'ids', $ids );
    }
}
