<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneActiveBySlug($slug) {
        return $this->createQueryBuilder( 'page' )
            ->where( 'page.isActive = :status' )
            ->andWhere( 'page.slug = :slug' )
            ->setMaxResults(1)
            ->setParameter( 'status', true )
            ->setParameter( 'slug', $slug )
            ->getQuery()
            ->getResult();
    }
}
