<?php

namespace AppBundle\Repository;

/**
 * ParserErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
