<?php

namespace AppBundle\Repository;

/**
 * ParserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserLogRepository extends \Doctrine\ORM\EntityRepository
{
}
