<?php

namespace AppBundle\Repository;

/**
 * PictureColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureColorRepository extends \Doctrine\ORM\EntityRepository
{
}
