<?php

namespace AppBundle\Repository;

/**
 * PictureFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureFormRepository extends \Doctrine\ORM\EntityRepository
{
}
