<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository {

    const LATEST_OFFSET = 0;
    const LATEST_LIMIT = 5;

    /**
     * @return array
     */
    public function getLatestReviews() {
        return $this->createQueryBuilder( 'review' )
                    ->where( 'review.isActive = :isActive' )
                    ->orderBy( 'review.updatedAt', 'DESC' )
                    ->setFirstResult( self::LATEST_OFFSET )
                    ->setMaxResults( self::LATEST_LIMIT )
                    ->setParameter( 'isActive', true )
                    ->getQuery()
                    ->getResult();
    }

    /**
     * @return QueryBuilder
     */
    public function getActiveReviews() {
        return $this->createQueryBuilder( 'review' )
            ->where( 'review.isActive = :isActive' )
            ->orderBy( 'review.updatedAt', 'DESC' )
            ->setParameter( 'isActive', true );
    }
}
