<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository {
    const LATEST_OFFSET = 0;
    const LATEST_LIMIT = 10;

    public function getSliders() {
        return $this->createQueryBuilder( 'slider' )
                    ->innerJoin( 'AppBundle:Image', 'img' )
                    ->where( 'slider.isActive = :isActive' )
                    ->orderBy( 'slider.id', 'DESC' )
                    ->setFirstResult( self::LATEST_OFFSET )
                    ->setMaxResults( self::LATEST_LIMIT )
                    ->setParameter( 'isActive', true )
                    ->getQuery()
                    ->getResult();
    }
}
