<?php

namespace AppBundle\Repository;

/**
 * UnderframeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnderframeRepository extends \Doctrine\ORM\EntityRepository
{
}
