sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:  [admin]
    sonata.user.block.menu:  # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes


sonata_user:
  security_acl: true # Uncomment for ACL support
  manager_type: orm # can be orm or mongodb
#  class:
#      user: AppBundle\Entity\User
#      group: AppBundle\Entity\Group

#sonata_classification:
#    class:
#        tag:          AppBundle\Entity\Tag
#        category:     AppBundle\Entity\Category
#        collection:   AppBundle\Entity\Collection
#        media:        AppBundle\Entity\Media
#        context:      AppBundle\Entity\Context
#
#    admin:
#        tag:
#            class:        Sonata\ClassificationBundle\Admin\TagAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle
#        category:
#            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
#            controller:   SonataClassificationBundle:CategoryAdmin
#            translation:  SonataClassificationBundle
#        collection:
#            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle
#        context:
#            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
#            controller:   SonataAdminBundle:CRUD
#            translation:  SonataClassificationBundle

sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl

#        role_admin: ROLE_ADMIN
#        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            EDITOR:   [EDIT, LIST, CREATE, OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    templates:
        layout: AppBundle::Admin\standard_layout.html.twig